version: '3.8'
services:
  mongodb-service:
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=demo
    command: mongod --auth
    ports:
      - '27017:27017'
    volumes:
      - mongodb-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

volumes:
  mongodb-volume:
